version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/multi_tenant_inventory
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: multi_tenant_inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
